![Bikeshare Insights Header Image](bike_share_header.png)

# Bikeshare Insights: Summer in the Windy City 

This dataset contains information on Divvy Bikes, a bikeshare program that provides residents and visitors of Chicago with a convenient way to explore the city. 

The workspace is set up with one CSV file containing bikeshare activities at the peak of the summer-July 2023. Columns include ride ID, bike type, start and end times, station names and IDs, location coordinates, and member type. Feel free to make this workspace yours by adding and removing cells, or editing any of the existing cells.

[Source: Divvy Bikes](https://divvybikes.com/system-data)

### 🌎 **Some guiding questions to help you explore this data:**
1. How many observations are in the dataset? Are there null values? 
2. How would you clean and prepare the data for analysis?
3. Which bike types are popular and which ones aren't? Check if being a member or casual rider makes a difference in bike choice.
4. Time check! What are the peak and off-peak riding times during the day?

### 📊 **Visualization ideas**
- Bar chart: Display the number of times each bike type is used to identify the most and least used bikes.
- Grouped bar chart: Compare bike usage by member type (member vs. casual) to see if it affects bike choice.
- Heatmap: Vividly illustrate the popularity of bikes at different times during the day and week.

You can query the pre-loaded CSV files using SQL directly. Here’s a **sample query**:

In [ ]:
SELECT rideable_type, start_station_name
FROM '202307-divvy-tripdata.parquet'
LIMIT 10

   rideable_type        start_station_name
0  electric_bike     Kedzie Ave & 110th St
1   classic_bike   Western Ave & Walton St
2   classic_bike   Western Ave & Walton St
3  electric_bike  Racine Ave & Randolph St
4   classic_bike     Clark St & Leland Ave
5   classic_bike  Racine Ave & Randolph St
6   classic_bike     Clark St & Leland Ave
7   classic_bike     Clark St & Leland Ave
8  electric_bike     Clark St & Leland Ave
9   classic_bike          Warren Park East

In [ ]:
import pandas as pd
divvy_jan2023 = pd.read_parquet("202307-divvy-tripdata.parquet")
divvy_jan2023.head()

            ride_id  rideable_type  ...    end_lng member_casual
0  9340B064F0AEE130  electric_bike  ... -87.653041        member
1  D1460EE3CE0D8AF8   classic_bike  ... -87.648384        member
2  DF41BE31B895A25E   classic_bike  ... -87.677692        member
3  9624A293749EF703  electric_bike  ... -87.641190        member
4  2F68A6A4CDB4C99A   classic_bike  ... -87.638181        member

[5 rows x 13 columns]

## Ready to share your work?

Click "Share" in the upper right corner, copy the link, and share it! You can also add this workspace to your DataCamp Portfolio